# Question 4: Database Integration

In [1]:
import pandas as pd
import numpy as np
import mysql.connector

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="******",
    database="ndta63_database"
)

cursor = connection.cursor()

print("MySQL connection successful!")

MySQL connection successful!

## Load the datasets

In [3]:


employment = pd.read_csv(
    r"C:\Users\Admin\Downloads\WB_AFS.csv",
    low_memory=False
)

freedom = pd.read_csv(
    r"C:\Users\Admin\Downloads\FH_FIW.csv",
    low_memory=False
)

print("Employment dataset loaded successfully!")
print("Freedom dataset loaded successfully!")

print("\nEmployment shape:", employment.shape)
print("Freedom shape:", freedom.shape)

Employment dataset loaded successfully!
Freedom dataset loaded successfully!

Employment shape: (4287, 41)
Freedom shape: (109920, 41)

In [4]:


print("EMPLOYMENT COLUMNS:")
print(employment.columns.tolist())

print("\n" + "=" * 80)

print("FREEDOM COLUMNS:")
print(freedom.columns.tolist())

EMPLOYMENT COLUMNS:
['STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'REF_AREA', 'INDICATOR', 'SEX', 'AGE', 'URBANISATION', 'UNIT_MEASURE', 'COMP_BREAKDOWN_1', 'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_3', 'TIME_PERIOD', 'OBS_VALUE', 'AGG_METHOD', 'UNIT_TYPE', 'DECIMALS', 'DATABASE_ID', 'TIME_FORMAT', 'UNIT_MULT', 'OBS_STATUS', 'OBS_CONF', 'FREQ_LABEL', 'REF_AREA_LABEL', 'INDICATOR_LABEL', 'SEX_LABEL', 'AGE_LABEL', 'URBANISATION_LABEL', 'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1_LABEL', 'COMP_BREAKDOWN_2_LABEL', 'COMP_BREAKDOWN_3_LABEL', 'AGG_METHOD_LABEL', 'UNIT_TYPE_LABEL', 'DECIMALS_LABEL', 'DATABASE_ID_LABEL', 'TIME_FORMAT_LABEL', 'UNIT_MULT_LABEL', 'OBS_STATUS_LABEL', 'OBS_CONF_LABEL']

================================================================================
FREEDOM COLUMNS:
['STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'REF_AREA', 'INDICATOR', 'SEX', 'AGE', 'URBANISATION', 'UNIT_MEASURE', 'COMP_BREAKDOWN_1', 'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_3', 'TIME_PERIOD', 'OBS_VALUE', 'AGG_METHOD', 'UNIT_TYPE', 'DECIMALS', 'DATABASE_ID', 'TIME_FORMAT', 'UNIT_MULT', 'OBS_STATUS', 'OBS_CONF', 'FREQ_LABEL', 'REF_AREA_LABEL', 'INDICATOR_LABEL', 'SEX_LABEL', 'AGE_LABEL', 'URBANISATION_LABEL', 'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1_LABEL', 'COMP_BREAKDOWN_2_LABEL', 'COMP_BREAKDOWN_3_LABEL', 'AGG_METHOD_LABEL', 'UNIT_TYPE_LABEL', 'DECIMALS_LABEL', 'DATABASE_ID_LABEL', 'TIME_FORMAT_LABEL', 'UNIT_MULT_LABEL', 'OBS_STATUS_LABEL', 'OBS_CONF_LABEL']

## Filter data for South Africa

In [5]:


employment_sa = employment[
    employment["REF_AREA"] == "ZAF"
].copy()

freedom_sa = freedom[
    freedom["REF_AREA"] == "ZAF"
].copy()

print("South Africa Employment data shape:")
print(employment_sa.shape)

print("\nSouth Africa Freedom data shape:")
print(freedom_sa.shape)

South Africa Employment data shape:
(25, 41)

South Africa Freedom data shape:
(560, 41)

In [6]:


columns_to_keep = [
    "REF_AREA",
    "REF_AREA_LABEL",
    "INDICATOR",
    "INDICATOR_LABEL",
    "TIME_PERIOD",
    "OBS_VALUE"
]

employment_db = employment_sa[columns_to_keep].copy()
freedom_db = freedom_sa[columns_to_keep].copy()

print("Employment database data:")
display(employment_db.head())

print("\nEmployment shape:", employment_db.shape)

print("\nFreedom database data:")
display(freedom_db.head())

print("\nFreedom shape:", freedom_db.shape)

Employment database data:

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,TIME_PERIOD,OBS_VALUE
4212,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2000,11.927134
4213,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2001,12.119992
4214,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2002,11.811001
4215,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2003,12.127343
4216,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2004,12.505107

Employment shape: (25, 6)

Freedom database data:

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,TIME_PERIOD,OBS_VALUE
45,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2024,2
241,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2023,2
437,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2022,2
633,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2021,2
829,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2020,2

Freedom shape: (560, 6)

In [7]:

employment_db["TIME_PERIOD"] = pd.to_numeric(
    employment_db["TIME_PERIOD"],
    errors="coerce"
)

freedom_db["TIME_PERIOD"] = pd.to_numeric(
    freedom_db["TIME_PERIOD"],
    errors="coerce"
)


employment_db["OBS_VALUE"] = pd.to_numeric(
    employment_db["OBS_VALUE"],
    errors="coerce"
)

freedom_db["OBS_VALUE"] = pd.to_numeric(
    freedom_db["OBS_VALUE"],
    errors="coerce"
)


print("EMPLOYMENT DATA TYPES:")
print(employment_db.dtypes)

print("\nFREEDOM DATA TYPES:")
print(freedom_db.dtypes)

EMPLOYMENT DATA TYPES:
REF_AREA            object
REF_AREA_LABEL      object
INDICATOR           object
INDICATOR_LABEL     object
TIME_PERIOD          int64
OBS_VALUE          float64
dtype: object

FREEDOM DATA TYPES:
REF_AREA            object
REF_AREA_LABEL      object
INDICATOR           object
INDICATOR_LABEL     object
TIME_PERIOD          int64
OBS_VALUE          float64
dtype: object

In [8]:


print("Missing values in Employment database data:")
print(employment_db.isnull().sum())

print("\nMissing values in Freedom database data:")
print(freedom_db.isnull().sum())

Missing values in Employment database data:
REF_AREA           0
REF_AREA_LABEL     0
INDICATOR          0
INDICATOR_LABEL    0
TIME_PERIOD        0
OBS_VALUE          0
dtype: int64

Missing values in Freedom database data:
REF_AREA            0
REF_AREA_LABEL      0
INDICATOR           0
INDICATOR_LABEL     0
TIME_PERIOD         0
OBS_VALUE          23
dtype: int64

In [9]:


employment_db = employment_db.dropna(
    subset=["OBS_VALUE"]
).copy()

freedom_db = freedom_db.dropna(
    subset=["OBS_VALUE"]
).copy()

print("Employment rows after cleaning:", len(employment_db))
print("Freedom rows after cleaning:", len(freedom_db))

print("\nMissing Employment OBS_VALUE:",
      employment_db["OBS_VALUE"].isnull().sum())

print("Missing Freedom OBS_VALUE:",
      freedom_db["OBS_VALUE"].isnull().sum())

Employment rows after cleaning: 25
Freedom rows after cleaning: 537

Missing Employment OBS_VALUE: 0
Missing Freedom OBS_VALUE: 0

In [10]:


if connection.is_connected():
    print("MySQL connection is active.")
else:
    print("MySQL connection is not active.")

MySQL connection is active.

## Create MySQL tables

In [11]:


create_employment_table = """
CREATE TABLE IF NOT EXISTS employment_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ref_area VARCHAR(10),
    country VARCHAR(100),
    indicator VARCHAR(100),
    indicator_name TEXT,
    year INT,
    value DOUBLE
)
"""

create_freedom_table = """
CREATE TABLE IF NOT EXISTS freedom_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ref_area VARCHAR(10),
    country VARCHAR(100),
    indicator VARCHAR(100),
    indicator_name TEXT,
    year INT,
    value DOUBLE
)
"""

cursor.execute(create_employment_table)
cursor.execute(create_freedom_table)

connection.commit()

print("Employment table created successfully!")
print("Freedom table created successfully!")

Employment table created successfully!
Freedom table created successfully!

In [12]:

cursor.execute("SHOW TABLES")

tables = cursor.fetchall()

print("Tables in ndta63_database:")

for table in tables:
    print(table[0])

Tables in ndta63_database:
employment_data
freedom_data

In [13]:


cursor.execute("DESCRIBE employment_data")

print("EMPLOYMENT TABLE STRUCTURE:")
for row in cursor.fetchall():
    print(row)

print("\n" + "=" * 80)


cursor.execute("DESCRIBE freedom_data")

print("FREEDOM TABLE STRUCTURE:")
for row in cursor.fetchall():
    print(row)

EMPLOYMENT TABLE STRUCTURE:
('id', 'int', 'NO', 'PRI', None, 'auto_increment')
('ref_area', 'varchar(10)', 'YES', '', None, '')
('country', 'varchar(100)', 'YES', '', None, '')
('indicator', 'varchar(100)', 'YES', '', None, '')
('indicator_name', 'text', 'YES', '', None, '')
('year', 'int', 'YES', '', None, '')
('value', 'double', 'YES', '', None, '')

================================================================================
FREEDOM TABLE STRUCTURE:
('id', 'int', 'NO', 'PRI', None, 'auto_increment')
('ref_area', 'varchar(10)', 'YES', '', None, '')
('country', 'varchar(100)', 'YES', '', None, '')
('indicator', 'varchar(100)', 'YES', '', None, '')
('indicator_name', 'text', 'YES', '', None, '')
('year', 'int', 'YES', '', None, '')
('value', 'double', 'YES', '', None, '')

## Prepare data for database integration

In [14]:


employment_insert = employment_db[
    [
        "REF_AREA",
        "REF_AREA_LABEL",
        "INDICATOR",
        "INDICATOR_LABEL",
        "TIME_PERIOD",
        "OBS_VALUE"
    ]
].copy()

employment_insert.columns = [
    "ref_area",
    "country",
    "indicator",
    "indicator_name",
    "year",
    "value"
]

print(employment_insert.head())
print("\nEmployment records ready for MySQL:", len(employment_insert))

     ref_area       country    indicator             indicator_name  year  \
4212      ZAF  South Africa  AG_SH_OFFFR  Off-Farm Employment Share  2000
4213      ZAF  South Africa  AG_SH_OFFFR  Off-Farm Employment Share  2001
4214      ZAF  South Africa  AG_SH_OFFFR  Off-Farm Employment Share  2002
4215      ZAF  South Africa  AG_SH_OFFFR  Off-Farm Employment Share  2003
4216      ZAF  South Africa  AG_SH_OFFFR  Off-Farm Employment Share  2004

          value
4212  11.927134
4213  12.119992
4214  11.811001
4215  12.127343
4216  12.505107

Employment records ready for MySQL: 25

In [15]:


freedom_insert = freedom_db[
    [
        "REF_AREA",
        "REF_AREA_LABEL",
        "INDICATOR",
        "INDICATOR_LABEL",
        "TIME_PERIOD",
        "OBS_VALUE"
    ]
].copy()

freedom_insert.columns = [
    "ref_area",
    "country",
    "indicator",
    "indicator_name",
    "year",
    "value"
]

print(freedom_insert.head())
print("\nFreedom records ready for MySQL:", len(freedom_insert))

    ref_area       country  indicator  \
45       ZAF  South Africa  FH_FIW_F3
241      ZAF  South Africa  FH_FIW_F3
437      ZAF  South Africa  FH_FIW_F3
633      ZAF  South Africa  FH_FIW_F3
829      ZAF  South Africa  FH_FIW_F3

                                        indicator_name  year  value
45   Rule of Law: Is there protection from the ille...  2024    2.0
241  Rule of Law: Is there protection from the ille...  2023    2.0
437  Rule of Law: Is there protection from the ille...  2022    2.0
633  Rule of Law: Is there protection from the ille...  2021    2.0
829  Rule of Law: Is there protection from the ille...  2020    2.0

Freedom records ready for MySQL: 537

## Insert data into MySQL

In [16]:
# Clear existing database records before inserting fresh data

cursor.execute("DELETE FROM employment_data")
cursor.execute("DELETE FROM freedom_data")

connection.commit()

print("Database tables cleared successfully.")

Database tables cleared successfully.

In [17]:


employment_sql = """
INSERT INTO employment_data
(ref_area, country, indicator, indicator_name, year, value)
VALUES (%s, %s, %s, %s, %s, %s)
"""

employment_data = [
    tuple(row)
    for row in employment_insert.itertuples(index=False, name=None)
]

cursor.executemany(employment_sql, employment_data)

connection.commit()

print(f"{len(employment_data)} Employment records inserted successfully!")

25 Employment records inserted successfully!

In [18]:


freedom_sql = """
INSERT INTO freedom_data
(ref_area, country, indicator, indicator_name, year, value)
VALUES (%s, %s, %s, %s, %s, %s)
"""

freedom_data = [
    tuple(row)
    for row in freedom_insert.itertuples(index=False, name=None)
]

cursor.executemany(freedom_sql, freedom_data)

connection.commit()

print(f"{len(freedom_data)} Freedom records inserted successfully!")

537 Freedom records inserted successfully!

In [19]:


cursor.execute("""
SELECT *
FROM employment_data
LIMIT 10
""")

employment_results = cursor.fetchall()

print("First 10 Employment records from MySQL:")

for row in employment_results:
    print(row)

First 10 Employment records from MySQL:
(434, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2000, 11.927134)
(435, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2001, 12.119992)
(436, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2002, 11.811001)
(437, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2003, 12.127343)
(438, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2004, 12.505107)
(439, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2005, 12.883156)
(440, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2006, 12.626928)
(441, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2007, 12.645207)
(442, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2008, 11.886748)
(443, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2009, 12.074104)

In [20]:


cursor.execute("""
SELECT *
FROM freedom_data
LIMIT 10
""")

freedom_results = cursor.fetchall()

print("First 10 Freedom records from MySQL:")

for row in freedom_results:
    print(row)

First 10 Freedom records from MySQL:
(9130, 'ZAF', 'South Africa', 'FH_FIW_F3', 'Rule of Law: Is there protection from the illegitimate use of physical force and freedom from war and insurgencies?', 2024, 2.0)
(9131, 'ZAF', 'South Africa', 'FH_FIW_F3', 'Rule of Law: Is there protection from the illegitimate use of physical force and freedom from war and insurgencies?', 2023, 2.0)
(9132, 'ZAF', 'South Africa', 'FH_FIW_F3', 'Rule of Law: Is there protection from the illegitimate use of physical force and freedom from war and insurgencies?', 2022, 2.0)
(9133, 'ZAF', 'South Africa', 'FH_FIW_F3', 'Rule of Law: Is there protection from the illegitimate use of physical force and freedom from war and insurgencies?', 2021, 2.0)
(9134, 'ZAF', 'South Africa', 'FH_FIW_F3', 'Rule of Law: Is there protection from the illegitimate use of physical force and freedom from war and insurgencies?', 2020, 2.0)
(9135, 'ZAF', 'South Africa', 'FH_FIW_F3', 'Rule of Law: Is there protection from the illegitimate use of physical force and freedom from war and insurgencies?', 2019, 2.0)
(9136, 'ZAF', 'South Africa', 'FH_FIW_F3', 'Rule of Law: Is there protection from the illegitimate use of physical force and freedom from war and insurgencies?', 2018, 2.0)
(9137, 'ZAF', 'South Africa', 'FH_FIW_F3', 'Rule of Law: Is there protection from the illegitimate use of physical force and freedom from war and insurgencies?', 2017, 2.0)
(9138, 'ZAF', 'South Africa', 'FH_FIW_F3', 'Rule of Law: Is there protection from the illegitimate use of physical force and freedom from war and insurgencies?', 2016, 2.0)
(9139, 'ZAF', 'South Africa', 'FH_FIW_F3', 'Rule of Law: Is there protection from the illegitimate use of physical force and freedom from war and insurgencies?', 2015, 2.0)

In [21]:


cursor.execute("""
SELECT *
FROM employment_data
WHERE ref_area = 'ZAF'
""")

results = cursor.fetchall()

print("South African Employment records:")
for row in results:
    print(row)

print("\nTotal records returned:", len(results))

South African Employment records:
(434, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2000, 11.927134)
(435, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2001, 12.119992)
(436, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2002, 11.811001)
(437, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2003, 12.127343)
(438, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2004, 12.505107)
(439, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2005, 12.883156)
(440, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2006, 12.626928)
(441, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2007, 12.645207)
(442, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2008, 11.886748)
(443, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2009, 12.074104)
(444, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2010, 12.257574)
(445, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2011, 11.772565)
(446, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2012, 12.267024)
(447, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2013, 12.507699)
(448, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2014, 12.65408)
(449, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2015, 12.855394)
(450, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2016, 12.880799)
(451, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2017, 13.084312)
(452, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2018, 13.390205)
(453, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2019, 13.4860325)
(454, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2020, 12.992733)
(455, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2021, 12.969736)
(456, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2022, 13.098627)
(457, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2023, 13.384285)
(458, 'ZAF', 'South Africa', 'AG_SH_OFFFR', 'Off-Farm Employment Share', 2024, 13.444483)

Total records returned: 25

In [22]:


cursor.execute("""
SELECT year, value
FROM employment_data
ORDER BY value DESC
""")

results = cursor.fetchall()

print("Employment values from highest to lowest:")

for row in results:
    print(row)

Employment values from highest to lowest:
(2019, 13.4860325)
(2024, 13.444483)
(2018, 13.390205)
(2023, 13.384285)
(2022, 13.098627)
(2017, 13.084312)
(2020, 12.992733)
(2021, 12.969736)
(2005, 12.883156)
(2016, 12.880799)
(2015, 12.855394)
(2014, 12.65408)
(2007, 12.645207)
(2006, 12.626928)
(2013, 12.507699)
(2004, 12.505107)
(2012, 12.267024)
(2010, 12.257574)
(2003, 12.127343)
(2001, 12.119992)
(2009, 12.074104)
(2000, 11.927134)
(2008, 11.886748)
(2002, 11.811001)
(2011, 11.772565)

In [23]:


cursor.execute("""
SELECT year, AVG(value) AS average_freedom_score
FROM freedom_data
GROUP BY year
ORDER BY year
""")

results = cursor.fetchall()

print("Average Freedom score by year:")

for row in results:
    print(row)

Average Freedom score by year:
(2013, 8.41025641025641)
(2014, 8.41025641025641)
(2015, 8.41025641025641)
(2016, 8.205128205128204)
(2017, 8.102564102564102)
(2018, 8.31578947368421)
(2019, 8.421052631578947)
(2020, 8.421052631578947)
(2021, 8.421052631578947)
(2022, 8.421052631578947)
(2023, 8.421052631578947)
(2024, 8.421052631578947)
(2025, 8.631578947368421)
(2026, 8.631578947368421)

In [24]:


cursor.execute("""
SELECT
    MIN(value) AS minimum_value,
    MAX(value) AS maximum_value,
    AVG(value) AS average_value
FROM freedom_data
""")

result = cursor.fetchone()

print("Freedom data statistics:")
print("Minimum:", result[0])
print("Maximum:", result[1])
print("Average:", result[2])

Freedom data statistics:
Minimum: 0.0
Maximum: 81.0
Average: 8.402234636871508

In [25]:


cursor.execute("""
SELECT indicator, COUNT(*) AS record_count
FROM freedom_data
GROUP BY indicator
ORDER BY record_count DESC
""")

results = cursor.fetchall()

print("Records per Freedom indicator:")

for row in results:
    print(row)

Records per Freedom indicator:
('FH_FIW_F3', 14)
('FH_FIW_F4', 14)
('FH_FIW_F', 14)
('FH_FIW_G1', 14)
('FH_FIW_G2', 14)
('FH_FIW_G3', 14)
('FH_FIW_G4', 14)
('FH_FIW_G', 14)
('FH_FIW_CL', 14)
('FH_FIW_TOTAL', 14)
('FH_FIW_D2', 14)
('FH_FIW_D3', 14)
('FH_FIW_D4', 14)
('FH_FIW_D', 14)
('FH_FIW_E1', 14)
('FH_FIW_E2', 14)
('FH_FIW_E3', 14)
('FH_FIW_E', 14)
('FH_FIW_F1', 14)
('FH_FIW_F2', 14)
('FH_FIW_B4', 14)
('FH_FIW_B', 14)
('FH_FIW_C1', 14)
('FH_FIW_C2', 14)
('FH_FIW_C3', 14)
('FH_FIW_C', 14)
('FH_FIW_ADD_Q', 14)
('FH_FIW_PR', 14)
('FH_FIW_D1', 14)
('FH_FIW_PR_RATING', 14)
('FH_FIW_CL_RATING', 14)
('FH_FIW_A1', 14)
('FH_FIW_A2', 14)
('FH_FIW_A3', 14)
('FH_FIW_A', 14)
('FH_FIW_B1', 14)
('FH_FIW_B2', 14)
('FH_FIW_B3', 14)
('FH_FIW_ADD_A', 5)

In [26]:


query = """
SELECT
    ref_area,
    country,
    indicator,
    indicator_name,
    year,
    value
FROM freedom_data
"""

freedom_from_mysql = pd.read_sql(query, connection)

print("Freedom data retrieved from MySQL:")
display(freedom_from_mysql.head())

print("\nShape:", freedom_from_mysql.shape)

Freedom data retrieved from MySQL:

C:\Users\Admin\AppData\Local\Temp\ipykernel_43988\4079818570.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  freedom_from_mysql = pd.read_sql(query, connection)

,ref_area,country,indicator,indicator_name,year,value
0,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2024,2.0
1,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2023,2.0
2,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2022,2.0
3,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2021,2.0
4,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2020,2.0

Shape: (537, 6)

In [27]:


query = """
SELECT
    ref_area,
    country,
    indicator,
    indicator_name,
    year,
    value
FROM employment_data
"""

employment_from_mysql = pd.read_sql(query, connection)

print("Employment data retrieved from MySQL:")
display(employment_from_mysql.head())

print("\nShape:", employment_from_mysql.shape)

Employment data retrieved from MySQL:

C:\Users\Admin\AppData\Local\Temp\ipykernel_43988\841933358.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  employment_from_mysql = pd.read_sql(query, connection)

,ref_area,country,indicator,indicator_name,year,value
0,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2000,11.927134
1,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2001,12.119992
2,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2002,11.811001
3,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2003,12.127343
4,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2004,12.505107

Shape: (25, 6)

In [28]:


cursor.execute("SELECT COUNT(*) FROM employment_data")
employment_total = cursor.fetchone()[0]

cursor.execute("SELECT COUNT(*) FROM freedom_data")
freedom_total = cursor.fetchone()[0]

print("FINAL DATABASE CHECK")
print("====================")
print("Employment records:", employment_total)
print("Freedom records:", freedom_total)

if employment_total == 25 and freedom_total == 537:
    print("\nDatabase integration verified successfully!")
else:
    print("\nRecord counts do not match the expected totals.")

FINAL DATABASE CHECK
====================
Employment records: 25
Freedom records: 537

Database integration verified successfully!

In [29]:


print("EMPLOYMENT TABLE SCHEMA")
print("=======================")

cursor.execute("DESCRIBE employment_data")

for row in cursor.fetchall():
    print(row)

print("\nFREEDOM TABLE SCHEMA")
print("====================")

cursor.execute("DESCRIBE freedom_data")

for row in cursor.fetchall():
    print(row)

EMPLOYMENT TABLE SCHEMA
=======================
('id', 'int', 'NO', 'PRI', None, 'auto_increment')
('ref_area', 'varchar(10)', 'YES', '', None, '')
('country', 'varchar(100)', 'YES', '', None, '')
('indicator', 'varchar(100)', 'YES', '', None, '')
('indicator_name', 'text', 'YES', '', None, '')
('year', 'int', 'YES', '', None, '')
('value', 'double', 'YES', '', None, '')

FREEDOM TABLE SCHEMA
====================
('id', 'int', 'NO', 'PRI', None, 'auto_increment')
('ref_area', 'varchar(10)', 'YES', '', None, '')
('country', 'varchar(100)', 'YES', '', None, '')
('indicator', 'varchar(100)', 'YES', '', None, '')
('indicator_name', 'text', 'YES', '', None, '')
('year', 'int', 'YES', '', None, '')
('value', 'double', 'YES', '', None, '')

## Database operations

In [30]:

cursor.execute("""
SELECT id, year, value
FROM employment_data
ORDER BY id
LIMIT 1
""")

record = cursor.fetchone()

print("Original record:")
print(record)

record_id = record[0]
original_value = record[2]

temporary_value = original_value + 0.001

cursor.execute("""
UPDATE employment_data
SET value = %s
WHERE id = %s
""", (temporary_value, record_id))

connection.commit()

print("Updated value:", temporary_value)


cursor.execute("""
UPDATE employment_data
SET value = %s
WHERE id = %s
""", (original_value, record_id))

connection.commit()

print("Original value restored:", original_value)

Original record:
(434, 2000, 11.927134)
Updated value: 11.928134
Original value restored: 11.927134

In [31]:


cursor.execute("""
INSERT INTO employment_data
(ref_area, country, indicator, indicator_name, year, value)
VALUES (%s, %s, %s, %s, %s, %s)
""", (
    "TEST",
    "Test Country",
    "TEST_INDICATOR",
    "Temporary Delete Test",
    9999,
    0.0
))

connection.commit()

temporary_id = cursor.lastrowid

print("Temporary record created.")
print("Temporary record ID:", temporary_id)

cursor.execute("""
DELETE FROM employment_data
WHERE id = %s
""", (temporary_id,))

connection.commit()

print("Temporary record deleted successfully.")

cursor.execute("""
SELECT COUNT(*)
FROM employment_data
WHERE id = %s
""", (temporary_id,))

remaining = cursor.fetchone()[0]

print("Remaining temporary records:", remaining)

Temporary record created.
Temporary record ID: 459
Temporary record deleted successfully.
Remaining temporary records: 0

In [32]:


cursor.execute("SELECT COUNT(*) FROM employment_data")
employment_total = cursor.fetchone()[0]

cursor.execute("SELECT COUNT(*) FROM freedom_data")
freedom_total = cursor.fetchone()[0]

print("FINAL DATABASE CHECK")
print("====================")
print("Employment records:", employment_total)
print("Freedom records:", freedom_total)

if employment_total == 25 and freedom_total == 537:
    print("\nDatabase data is complete and correct!")
else:
    print("\nWARNING: Record counts do not match expected totals.")

FINAL DATABASE CHECK
====================
Employment records: 25
Freedom records: 537

Database data is complete and correct!

## Retrieve data from MySQL

In [33]:


employment_from_mysql = pd.read_sql("""
SELECT
    ref_area,
    country,
    indicator,
    indicator_name,
    year,
    value
FROM employment_data
""", connection)

freedom_from_mysql = pd.read_sql("""
SELECT
    ref_area,
    country,
    indicator,
    indicator_name,
    year,
    value
FROM freedom_data
""", connection)

print("Employment data retrieved from MySQL:")
display(employment_from_mysql.head())

print("\nFreedom data retrieved from MySQL:")
display(freedom_from_mysql.head())

print("\nEmployment shape:", employment_from_mysql.shape)
print("Freedom shape:", freedom_from_mysql.shape)

Employment data retrieved from MySQL:

C:\Users\Admin\AppData\Local\Temp\ipykernel_43988\1153801331.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  employment_from_mysql = pd.read_sql("""
C:\Users\Admin\AppData\Local\Temp\ipykernel_43988\1153801331.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  freedom_from_mysql = pd.read_sql("""

,ref_area,country,indicator,indicator_name,year,value
0,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2000,11.927134
1,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2001,12.119992
2,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2002,11.811001
3,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2003,12.127343
4,ZAF,South Africa,AG_SH_OFFFR,Off-Farm Employment Share,2004,12.505107

Freedom data retrieved from MySQL:

,ref_area,country,indicator,indicator_name,year,value
0,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2024,2.0
1,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2023,2.0
2,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2022,2.0
3,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2021,2.0
4,ZAF,South Africa,FH_FIW_F3,Rule of Law: Is there protection from the ille...,2020,2.0

Employment shape: (25, 6)
Freedom shape: (537, 6)

## Export database data

In [34]:


employment_from_mysql.to_csv(
    r"C:\Users\Admin\Downloads\Employment_From_MySQL_Final.csv",
    index=False
)

freedom_from_mysql.to_csv(
    r"C:\Users\Admin\Downloads\Freedom_From_MySQL_Final.csv",
    index=False
)

print("Employment CSV exported successfully.")
print("Freedom CSV exported successfully.")

print("\nEmployment rows exported:", len(employment_from_mysql))
print("Freedom rows exported:", len(freedom_from_mysql))

Employment CSV exported successfully.
Freedom CSV exported successfully.

Employment rows exported: 25
Freedom rows exported: 537

In [35]:


employment_check = pd.read_csv(
    r"C:\Users\Admin\Downloads\Employment_From_MySQL_Final.csv"
)

freedom_check = pd.read_csv(
    r"C:\Users\Admin\Downloads\Freedom_From_MySQL_Final.csv"
)

print("FINAL CSV CHECK")
print("================")
print("Employment file shape:", employment_check.shape)
print("Freedom file shape:", freedom_check.shape)

print("\nEmployment columns:")
print(employment_check.columns.tolist())

print("\nFreedom columns:")
print(freedom_check.columns.tolist())

FINAL CSV CHECK
================
Employment file shape: (25, 6)
Freedom file shape: (537, 6)

Employment columns:
['ref_area', 'country', 'indicator', 'indicator_name', 'year', 'value']

Freedom columns:
['ref_area', 'country', 'indicator', 'indicator_name', 'year', 'value']